test (python 3.5):
  image: python:3.5
  script:
    - echo 'python 3.5'
    # this configures Django application to use attached postgres database that is run on `postgres` host
#    - export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
#    - apt-get update -qy
#    - apt-get install -y python-dev python-pip python3-pip
#    - pip install -r requirements.txt
#    - tox -e py35
test (python 3.6):
  image: python:3.6
  script:
    - echo 'python 3.6'
    # this configures Django application to use attached postgres database that is run on `postgres` host
#    - export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
#    - apt-get update -qy
#    - apt-get install -y python-dev python-pip
#    - pip install -r requirements.txt
#    - tox -e py36

staging:
  image: coxauto/aws-ebcli
  type: deploy
  variables:
    PROJECT_ENV: develop
  environment:
    name: staging
    url: http://flaskgitlabci-staging.g2mtyzmnps.us-east-1.elasticbeanstalk.com/api/v1/home
  script:
    - chmod +x deploy.sh
    - ./deploy.sh
  only:
    - develop

production:
  image: coxauto/aws-ebcli
  script:
  - apt-get update -qy
  - apt-get install -y - python-dev python-pip
  - pip install awsebcli --upgrade --user
  - eb deploy --env-group-suffix prod
  only:
  - master
  when:
    - manual