test (python 3.5):
  image: python:3.5
  script:
    # this configures Django application to use attached postgres database that is run on `postgres` host
    - export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
    - apt-get update -qy
    - apt-get install -y python-dev python-pip python3-pip
    - pip install -r requirements.txt
    - tox -e py35
test (python 3.6):
  image: python:3.6
  script:
    # this configures Django application to use attached postgres database that is run on `postgres` host
    - export DATABASE_URL=postgres://postgres:@postgres:5432/python-test-app
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    - tox -e py36

staging:
  image: python:3.6
  type: deploy
  variables:
    PROJECT_ENV: develop
  environment: staging
  script:
    - pip install awsebcli --upgrade --ignore-installed
    - eb init eb-dev-pythonapp -p python -r ap-east-1
    - eb use FlaskGitlabCi-staging
    - eb deploy eb-dev-pythonenv -l eb-python-dev-$CI_COMMIT_SHA
  only:
  - develop

production:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y - python-dev python-pip
  - pip install awsebcli --upgrade --user
  - eb deploy --env-group-suffix prod
  only:
  - master
