version: 0.2

# env:
#   variables:
#     key: "value"
#     key: "value"
#   parameter-store:
#     key: "value"
#     key: "value"

phases:
  install:
    runtime-versions:
      python: 3.6
      # runtime: version
    commands:
      - pip install -r requirements.txt
  build:
    run-as: ubuntu
    commands:
      - tox -v
